# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created: Wed Jan 10 21:43:38 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(972, 569)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 951, 561))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.resim_goster1 = QtGui.QGraphicsView(self.tab)
        self.resim_goster1.setGeometry(QtCore.QRect(10, 10, 301, 261))
        self.resim_goster1.setObjectName(_fromUtf8("resim_goster1"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(320, 40, 271, 181))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.btn_gray = QtGui.QPushButton(self.groupBox)
        self.btn_gray.setGeometry(QtCore.QRect(20, 20, 121, 31))
        self.btn_gray.setObjectName(_fromUtf8("btn_gray"))
        self.btn_binary = QtGui.QPushButton(self.groupBox)
        self.btn_binary.setGeometry(QtCore.QRect(20, 50, 121, 31))
        self.btn_binary.setObjectName(_fromUtf8("btn_binary"))
        self.combo_rotate = QtGui.QComboBox(self.groupBox)
        self.combo_rotate.setGeometry(QtCore.QRect(140, 50, 121, 31))
        self.combo_rotate.setObjectName(_fromUtf8("combo_rotate"))
        self.combo_rotate.addItem(_fromUtf8(""))
        self.combo_rotate.addItem(_fromUtf8(""))
        self.combo_rotate.addItem(_fromUtf8(""))
        self.combo_rotate.addItem(_fromUtf8(""))
        self.combo_rotate.addItem(_fromUtf8(""))
        self.combo_rotate.addItem(_fromUtf8(""))
        self.txt_en = QtGui.QLineEdit(self.groupBox)
        self.txt_en.setGeometry(QtCore.QRect(40, 90, 91, 20))
        self.txt_en.setObjectName(_fromUtf8("txt_en"))
        self.txt_boy = QtGui.QLineEdit(self.groupBox)
        self.txt_boy.setGeometry(QtCore.QRect(140, 90, 91, 20))
        self.txt_boy.setObjectName(_fromUtf8("txt_boy"))
        self.btn_resize = QtGui.QPushButton(self.groupBox)
        self.btn_resize.setGeometry(QtCore.QRect(100, 120, 75, 23))
        self.btn_resize.setObjectName(_fromUtf8("btn_resize"))
        self.lbl_resize = QtGui.QLabel(self.groupBox)
        self.lbl_resize.setGeometry(QtCore.QRect(20, 160, 191, 16))
        self.lbl_resize.setObjectName(_fromUtf8("lbl_resize"))
        self.btn_piksel = QtGui.QPushButton(self.groupBox)
        self.btn_piksel.setGeometry(QtCore.QRect(140, 20, 121, 31))
        self.btn_piksel.setObjectName(_fromUtf8("btn_piksel"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 220, 271, 61))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.combo_filter = QtGui.QComboBox(self.groupBox_2)
        self.combo_filter.setGeometry(QtCore.QRect(30, 20, 171, 22))
        self.combo_filter.setObjectName(_fromUtf8("combo_filter"))
        self.combo_filter.addItem(_fromUtf8(""))
        self.combo_filter.addItem(_fromUtf8(""))
        self.combo_filter.addItem(_fromUtf8(""))
        self.resim_goster2 = QtGui.QGraphicsView(self.tab)
        self.resim_goster2.setGeometry(QtCore.QRect(610, 10, 301, 261))
        self.resim_goster2.setObjectName(_fromUtf8("resim_goster2"))
        self.btn_ryukle = QtGui.QPushButton(self.tab)
        self.btn_ryukle.setGeometry(QtCore.QRect(360, 0, 201, 31))
        self.btn_ryukle.setObjectName(_fromUtf8("btn_ryukle"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 280, 471, 251))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btn_hist_goster = QtGui.QPushButton(self.groupBox_3)
        self.btn_hist_goster.setGeometry(QtCore.QRect(20, 30, 141, 31))
        self.btn_hist_goster.setObjectName(_fromUtf8("btn_hist_goster"))
        self.btn_hist_esitle = QtGui.QPushButton(self.groupBox_3)
        self.btn_hist_esitle.setGeometry(QtCore.QRect(20, 70, 141, 31))
        self.btn_hist_esitle.setObjectName(_fromUtf8("btn_hist_esitle"))
        self.resim_goster3 = QtGui.QGraphicsView(self.groupBox_3)
        self.resim_goster3.setGeometry(QtCore.QRect(180, 10, 281, 231))
        self.resim_goster3.setObjectName(_fromUtf8("resim_goster3"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 110, 91, 41))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(100, 120, 61, 21))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.btn_hist_benzerlik = QtGui.QPushButton(self.groupBox_3)
        self.btn_hist_benzerlik.setGeometry(QtCore.QRect(20, 160, 131, 23))
        self.btn_hist_benzerlik.setObjectName(_fromUtf8("btn_hist_benzerlik"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(490, 290, 261, 231))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lbl_mse = QtGui.QLabel(self.groupBox_4)
        self.lbl_mse.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.lbl_mse.setObjectName(_fromUtf8("lbl_mse"))
        self.lbl_psnr = QtGui.QLabel(self.groupBox_4)
        self.lbl_psnr.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.lbl_psnr.setObjectName(_fromUtf8("lbl_psnr"))
        self.lbl_ssim = QtGui.QLabel(self.groupBox_4)
        self.lbl_ssim.setGeometry(QtCore.QRect(10, 70, 121, 16))
        self.lbl_ssim.setObjectName(_fromUtf8("lbl_ssim"))
        self.btn_benzerlik = QtGui.QPushButton(self.groupBox_4)
        self.btn_benzerlik.setGeometry(QtCore.QRect(10, 190, 131, 23))
        self.btn_benzerlik.setObjectName(_fromUtf8("btn_benzerlik"))
        self.lbl1 = QtGui.QLabel(self.groupBox_4)
        self.lbl1.setGeometry(QtCore.QRect(40, 40, 46, 13))
        self.lbl1.setObjectName(_fromUtf8("lbl1"))
        self.lbl2 = QtGui.QLabel(self.groupBox_4)
        self.lbl2.setGeometry(QtCore.QRect(40, 90, 46, 13))
        self.lbl2.setObjectName(_fromUtf8("lbl2"))
        self.lbl3 = QtGui.QLabel(self.groupBox_4)
        self.lbl3.setGeometry(QtCore.QRect(40, 150, 46, 13))
        self.lbl3.setObjectName(_fromUtf8("lbl3"))
        self.btn_gurultu = QtGui.QPushButton(self.groupBox_4)
        self.btn_gurultu.setGeometry(QtCore.QRect(120, 100, 91, 41))
        self.btn_gurultu.setObjectName(_fromUtf8("btn_gurultu"))
        self.verticalSlider = QtGui.QSlider(self.groupBox_4)
        self.verticalSlider.setGeometry(QtCore.QRect(220, 20, 22, 160))
        self.verticalSlider.setMinimum(0)
        self.verticalSlider.setMaximum(60)
        self.verticalSlider.setSingleStep(10)
        self.verticalSlider.setTracking(True)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.lbl_gurultu = QtGui.QLabel(self.groupBox_4)
        self.lbl_gurultu.setGeometry(QtCore.QRect(250, 190, 46, 13))
        self.lbl_gurultu.setText(_fromUtf8(""))
        self.lbl_gurultu.setObjectName(_fromUtf8("lbl_gurultu"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(760, 290, 141, 221))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.radio_eroison = QtGui.QRadioButton(self.groupBox_5)
        self.radio_eroison.setGeometry(QtCore.QRect(20, 40, 81, 51))
        self.radio_eroison.setObjectName(_fromUtf8("radio_eroison"))
        self.radio_dilation = QtGui.QRadioButton(self.groupBox_5)
        self.radio_dilation.setGeometry(QtCore.QRect(20, 90, 81, 61))
        self.radio_dilation.setObjectName(_fromUtf8("radio_dilation"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 341, 521))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.r_yukle_labelling = QtGui.QPushButton(self.groupBox_7)
        self.r_yukle_labelling.setGeometry(QtCore.QRect(20, 230, 111, 41))
        self.r_yukle_labelling.setObjectName(_fromUtf8("r_yukle_labelling"))
        self.r_goster_labelling1 = QtGui.QGraphicsView(self.groupBox_7)
        self.r_goster_labelling1.setGeometry(QtCore.QRect(10, 20, 301, 201))
        self.r_goster_labelling1.setObjectName(_fromUtf8("r_goster_labelling1"))
        self.btn_labelling = QtGui.QPushButton(self.groupBox_7)
        self.btn_labelling.setGeometry(QtCore.QRect(160, 230, 111, 41))
        self.btn_labelling.setObjectName(_fromUtf8("btn_labelling"))
        self.r_goster_labelling2 = QtGui.QGraphicsView(self.groupBox_7)
        self.r_goster_labelling2.setGeometry(QtCore.QRect(20, 280, 301, 231))
        self.r_goster_labelling2.setObjectName(_fromUtf8("r_goster_labelling2"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(370, 20, 471, 271))
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.combo_labelling = QtGui.QComboBox(self.groupBox_8)
        self.combo_labelling.setGeometry(QtCore.QRect(70, 20, 111, 31))
        self.combo_labelling.setObjectName(_fromUtf8("combo_labelling"))
        self.r_goster_labelling3 = QtGui.QGraphicsView(self.groupBox_8)
        self.r_goster_labelling3.setGeometry(QtCore.QRect(20, 60, 251, 191))
        self.r_goster_labelling3.setObjectName(_fromUtf8("r_goster_labelling3"))
        self.lbl_kare_mi = QtGui.QLabel(self.groupBox_8)
        self.lbl_kare_mi.setGeometry(QtCore.QRect(230, 20, 191, 16))
        self.lbl_kare_mi.setObjectName(_fromUtf8("lbl_kare_mi"))
        self.btn_karemi = QtGui.QPushButton(self.groupBox_8)
        self.btn_karemi.setGeometry(QtCore.QRect(310, 70, 111, 41))
        self.btn_karemi.setObjectName(_fromUtf8("btn_karemi"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.r_goster_mantik1 = QtGui.QGraphicsView(self.tab_3)
        self.r_goster_mantik1.setGeometry(QtCore.QRect(20, 10, 271, 251))
        self.r_goster_mantik1.setObjectName(_fromUtf8("r_goster_mantik1"))
        self.r_yukle_mantik1 = QtGui.QPushButton(self.tab_3)
        self.r_yukle_mantik1.setGeometry(QtCore.QRect(80, 280, 121, 41))
        self.r_yukle_mantik1.setObjectName(_fromUtf8("r_yukle_mantik1"))
        self.r_yukle_mantik2 = QtGui.QPushButton(self.tab_3)
        self.r_yukle_mantik2.setGeometry(QtCore.QRect(650, 280, 121, 41))
        self.r_yukle_mantik2.setObjectName(_fromUtf8("r_yukle_mantik2"))
        self.combo_mantik = QtGui.QComboBox(self.tab_3)
        self.combo_mantik.setGeometry(QtCore.QRect(340, 60, 121, 41))
        self.combo_mantik.setObjectName(_fromUtf8("combo_mantik"))
        self.combo_mantik.addItem(_fromUtf8(""))
        self.combo_mantik.addItem(_fromUtf8(""))
        self.combo_mantik.addItem(_fromUtf8(""))
        self.combo_mantik.addItem(_fromUtf8(""))
        self.r_goster_mantik2 = QtGui.QGraphicsView(self.tab_3)
        self.r_goster_mantik2.setGeometry(QtCore.QRect(580, 10, 271, 251))
        self.r_goster_mantik2.setObjectName(_fromUtf8("r_goster_mantik2"))
        self.r_goster_mantik3 = QtGui.QGraphicsView(self.tab_3)
        self.r_goster_mantik3.setGeometry(QtCore.QRect(300, 120, 271, 241))
        self.r_goster_mantik3.setObjectName(_fromUtf8("r_goster_mantik3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.comboBox = QtGui.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(740, 310, 69, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 0, 391, 491))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.graphicsView = QtGui.QGraphicsView(self.groupBox_6)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 301, 201))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.pushButton = QtGui.QPushButton(self.groupBox_6)
        self.pushButton.setGeometry(QtCore.QRect(120, 240, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.graphicsView_3 = QtGui.QGraphicsView(self.groupBox_6)
        self.graphicsView_3.setGeometry(QtCore.QRect(20, 270, 301, 201))
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox.setTitle(_translate("Form", "Temel İşlemler", None))
        self.btn_gray.setText(_translate("Form", "Gray Resme Dönüştür", None))
        self.btn_binary.setText(_translate("Form", "Binary Resme Dönüştür", None))
        self.combo_rotate.setItemText(0, _translate("Form", "30", None))
        self.combo_rotate.setItemText(1, _translate("Form", "45", None))
        self.combo_rotate.setItemText(2, _translate("Form", "60", None))
        self.combo_rotate.setItemText(3, _translate("Form", "90", None))
        self.combo_rotate.setItemText(4, _translate("Form", "180", None))
        self.combo_rotate.setItemText(5, _translate("Form", "270", None))
        self.btn_resize.setText(_translate("Form", "Resize Et", None))
        self.lbl_resize.setText(_translate("Form", "Resize İşlemi Başarısı:", None))
        self.btn_piksel.setText(_translate("Form", "Pikselleri Göster", None))
        self.groupBox_2.setTitle(_translate("Form", "Filtreleme İşlemleri", None))
        self.combo_filter.setItemText(0, _translate("Form", "Canny", None))
        self.combo_filter.setItemText(1, _translate("Form", "Sobel", None))
        self.combo_filter.setItemText(2, _translate("Form", "Prewit", None))
        self.btn_ryukle.setText(_translate("Form", "Resim Yükle", None))
        self.groupBox_3.setTitle(_translate("Form", "Histogram İşlemleri", None))
        self.btn_hist_goster.setText(_translate("Form", "Histogram Grafiğini Göster", None))
        self.btn_hist_esitle.setText(_translate("Form", "Histogram Eşitle", None))
        self.label.setText(_translate("Form", "Benzerlik Oranı:", None))
        self.btn_hist_benzerlik.setText(_translate("Form", "Histogram Benzerliği", None))
        self.groupBox_4.setTitle(_translate("Form", "Gürültü Oluştur", None))
        self.lbl_mse.setText(_translate("Form", "mse benzerlik oranı:", None))
        self.lbl_psnr.setText(_translate("Form", "psnr benzerlik oranı:", None))
        self.lbl_ssim.setText(_translate("Form", "ssim benzerlik oranı:", None))
        self.btn_benzerlik.setText(_translate("Form", "Benzerlik Hesapla", None))
        self.lbl1.setText(_translate("Form", "TextLabel", None))
        self.lbl2.setText(_translate("Form", "TextLabel", None))
        self.lbl3.setText(_translate("Form", "TextLabel", None))
        self.btn_gurultu.setText(_translate("Form", "Gürültü Yükle", None))
        self.groupBox_5.setTitle(_translate("Form", "Eroison/Dilation", None))
        self.radio_eroison.setText(_translate("Form", "Eroison", None))
        self.radio_dilation.setText(_translate("Form", "Dilation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Genel İşlemler", None))
        self.groupBox_7.setTitle(_translate("Form", "Labelling", None))
        self.r_yukle_labelling.setText(_translate("Form", "Resim Yükle", None))
        self.btn_labelling.setText(_translate("Form", "Labelling Yap", None))
        self.lbl_kare_mi.setText(_translate("Form", "Kare Kontrolü:", None))
        self.btn_karemi.setText(_translate("Form", "Kare Kontrölü", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Labellig", None))
        self.r_yukle_mantik1.setText(_translate("Form", "Birinci Resmi Seç", None))
        self.r_yukle_mantik2.setText(_translate("Form", "Ikinci Resmi Seç", None))
        self.combo_mantik.setItemText(0, _translate("Form", "NOT", None))
        self.combo_mantik.setItemText(1, _translate("Form", "AND", None))
        self.combo_mantik.setItemText(2, _translate("Form", "OR", None))
        self.combo_mantik.setItemText(3, _translate("Form", "XOR", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Mantiksal İşlemler", None))
        self.groupBox_6.setTitle(_translate("Form", "Labelling", None))
        self.pushButton.setText(_translate("Form", "Labelling Yap", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Template Matching", None))

